{
 "title": "Example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Average response time [3m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"example\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"kubernetes-service-endpoints\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"example\"}[3m])",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}